/* Productmodel*/
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(1,'Classic Vest ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(2,'Cycling Cap ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(3,'Full-Finger Gloves ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(4,'Half-Finger Gloves ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(5,'HL Mountain Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(6,'HL Road Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(7,'HL Touring Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(8,'LL Mountain Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(9,'LL Road Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(10,'LL Touring Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(11,'Long-Sleeve Logo Jersey ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(12,'Men''s Bib-Shorts ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(13,'Men''s Sports Shorts ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(14,'ML Mountain Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(15,'ML Mountain Frame-W ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(16,'ML Road Frame ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(17,'ML Road Frame-W ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(18,'Mountain Bike Socks ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(19,'Mountain-100 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(20,'Mountain-200 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(21,'Mountain-300 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(22,'Mountain-400-W ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(23,'Mountain-500 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(24,'Racing Socks ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(25,'Road-150 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(26,'Road-250 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(27,'Road-350-W ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(28,'Road-450 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(29,'Road-550-W ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(30,'Road-650 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(31,'Road-750 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(32,'Short-Sleeve Classic Jersey ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(33,'Sport-100 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(34,'Touring-1000 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(35,'Touring-2000 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(36,'Touring-3000 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(37,'Women''s Mountain Shorts ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(38,'Women''s Tights ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(39,'Mountain-400 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(40,'Road-550 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(41,'Road-350 ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(42,'LL Mountain Front Wheel ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(43,'Touring Rear Wheel ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(44,'Touring Front Wheel ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(45,'ML Mountain Front Wheel ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(46,'HL Mountain Front Wheel ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(47,'LL Touring Handlebars ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(48,'HL Touring Handlebars ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(49,'LL Road Front Wheel ',NULL);
insert into ProductModel(ProductModelID,Name,CatalogDescription) values(50,'ML Road Front Wheel ',NULL);