/* AD CATEGORÍAS */ 
ALTER TABLE PRODUCTCATEGORY ADD CONSTRAINT CK_NOMBREDOSPLABRAS CHECK (name LIKE '% %' AND name NOT LIKE '% % %');
ALTER TABLE PRODUCTCATEGORY ADD CONSTRAINT CK_NOMBREUNICO UNIQUE(name);
ALTER TABLE PRODUCTCATEGORY ADD CONSTRAINT CK_PADREDIFERENTENOMBRE CHECK (PARENTPRODUCTCATEGORYID != name);
INSERT INTO PRODUCTCATEGORY(NAME,PARENTPRODUCTCATEGORYID,PRODUCTCATEGORYID) VALUES ('adfa afd',1,1);