/*Poblar OK*/

---Poblado de departamentos
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (1,'Seguridad','Phasellus vitae mauris sit amet');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (2,'Seguridad','Sed eu nibh');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (3,'Atención Usuarios','nibh vulputate');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (4,'Pagos','commodo auctor velit. Aliquam nisl. Nulla');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (5,'Logistica','lacus pede sagittis augue, eu tempor');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (6,'Seguridad','leo elementum sem, vitae aliquam eros turpis non enim.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (7,'Pagos','venenatis lacus. Etiam');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (8,'Logistica','adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (9,'Atención Usuarios','primis in faucibus orci luctus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (10,'Aseo','sapien. Cras dolor dolor, tempus non,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (11,'Logistica','ullamcorper. Duis cursus, diam at');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (12,'Aseo','vel turpis. Aliquam adipiscing lobortis risus. In mi pede,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (13,'Logistica','velit in aliquet lobortis,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (14,'Atención Usuarios','dui nec urna suscipit nonummy. Fusce fermentum');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (15,'Seguridad','lacus. Ut nec urna');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (16,'Seguridad','eu tellus. Phasellus elit');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (17,'Aseo','et nunc. Quisque ornare tortor at risus.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (18,'Logistica','ac turpis');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (19,'Logistica','gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (20,'Logistica','auctor odio a purus.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (21,'Atención Usuarios','fringilla euismod enim.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (22,'Atención Usuarios','ac turpis');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (23,'Seguridad','ac facilisis facilisis, magna tellus faucibus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (24,'Logistica','montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (25,'Aseo','dui, semper et, lacinia vitae, sodales at,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (26,'Logistica','Suspendisse dui. Fusce diam nunc, ullamcorper');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (27,'Pagos','ac');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (28,'Aseo','ut lacus. Nulla tincidunt, neque vitae');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (29,'Logistica','In condimentum.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (30,'Pagos','sit amet risus. Donec egestas. Aliquam nec');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (31,'Logistica','iaculis enim, sit amet ornare lectus justo eu');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (32,'Atención Usuarios','a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (33,'Pagos','dui');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (34,'Aseo','Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (35,'Aseo','rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (36,'Atención Usuarios','feugiat tellus lorem eu metus.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (37,'Aseo','risus quis diam luctus lobortis.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (38,'Seguridad','dictum cursus. Nunc mauris elit, dictum');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (39,'Pagos','neque venenatis lacus. Etiam bibendum fermentum metus. Aenean');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (40,'Logistica','sapien. Nunc pulvinar arcu');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (41,'Atención Usuarios','In at pede. Cras vulputate velit eu sem. Pellentesque ut');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (42,'Aseo','in faucibus orci luctus et');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (43,'Atención Usuarios','augue id ante dictum cursus. Nunc mauris elit, dictum');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (44,'Seguridad','laoreet, libero');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (45,'Atención Usuarios','vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (46,'Pagos','est, vitae sodales nisi magna');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (47,'Atención Usuarios','facilisis, magna tellus faucibus leo, in lobortis');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (48,'Pagos','quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (49,'Logistica','Morbi');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (50,'Atención Usuarios','lacinia mattis. Integer eu lacus. Quisque imperdiet,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (51,'Seguridad','luctus.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (52,'Aseo','porttitor tellus non magna. Nam ligula elit,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (53,'Pagos','eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (54,'Pagos','euismod');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (55,'Logistica','amet, faucibus ut, nulla. Cras eu tellus eu');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (56,'Logistica','ornare. Fusce mollis. Duis sit amet diam eu');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (57,'Seguridad','Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (58,'Atención Usuarios','ultricies ligula. Nullam enim. Sed nulla ante,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (59,'Logistica','Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (60,'Atención Usuarios','eu enim. Etiam');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (61,'Pagos','natoque penatibus et magnis dis parturient');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (62,'Pagos','purus, accumsan');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (63,'Pagos','ipsum');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (64,'Seguridad','augue. Sed molestie. Sed id risus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (65,'Atención Usuarios','aliquet magna a neque. Nullam ut nisi a odio');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (66,'Seguridad','pede, ultrices a, auctor non, feugiat nec,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (67,'Logistica','dapibus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (68,'Logistica','non, luctus sit amet, faucibus ut, nulla. Cras eu tellus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (69,'Atención Usuarios','augue. Sed molestie. Sed id risus quis diam luctus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (70,'Pagos','tincidunt. Donec vitae erat vel pede blandit congue.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (71,'Logistica','et ultrices posuere cubilia Curae; Donec');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (72,'Logistica','arcu. Nunc');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (73,'Atención Usuarios','posuere');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (74,'Aseo','Nam consequat');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (75,'Pagos','nulla. Integer urna. Vivamus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (76,'Seguridad','neque. Nullam ut nisi');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (77,'Logistica','vestibulum, neque sed dictum eleifend, nunc risus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (78,'Atención Usuarios','Nunc ac sem');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (79,'Pagos','Nullam scelerisque');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (80,'Seguridad','vitae, sodales at,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (81,'Logistica','Ut');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (82,'Atención Usuarios','pede, malesuada');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (83,'Logistica','dui augue eu tellus. Phasellus elit pede,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (84,'Pagos','nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (85,'Seguridad','tellus eu augue porttitor interdum.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (86,'Seguridad','placerat. Cras dictum ultricies ligula. Nullam');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (87,'Pagos','dictum augue malesuada malesuada. Integer id magna et ipsum cursus');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (88,'Seguridad','elit, pharetra ut, pharetra sed, hendrerit');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (89,'Pagos','porta elit, a feugiat tellus lorem eu metus. In');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (90,'Pagos','congue.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (91,'Atención Usuarios','consequat');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (92,'Atención Usuarios','Maecenas libero est, congue a,');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (93,'Logistica','nunc sit');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (94,'Atención Usuarios','sagittis. Duis gravida.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (95,'Seguridad','quam a felis ullamcorper viverra. Maecenas iaculis aliquet');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (96,'Logistica','risus. Donec egestas. Duis ac');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (97,'Seguridad','euismod urna. Nullam lobortis quam a felis ullamcorper viverra.');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (98,'Seguridad','Morbi vehicula. Pellentesque tincidunt tempus risus. Donec');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (99,'Atención Usuarios','massa. Mauris vestibulum, neque sed');
INSERT INTO  Departamentos  ( ID , nombre , descripcion ) VALUES (100,'Atención Usuarios','lacus. Mauris non dui nec urna suscipit nonummy.');
